In [19]:
import torch
import numpy as np

**Trabajando con tensores**

In [18]:
torch.__version__

'1.3.0'

In [20]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [21]:
tensor_b = torch.Tensor(2,2)  #crea tensor del tamaño que se quiere con números aleatorios
print(tensor_b)
tensor_b.uniform_(0,1)  #crea tensor del tamaño que se quiere con números dentro del rango

tensor([[0.0000, 1.8750],
        [0.0000, 0.0000]])


tensor([[0.3816, 0.7369],
        [0.1570, 0.6490]])

In [22]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.0602, 0.9486],
        [0.5787, 0.0839]])

In [23]:
result = tensor_b + tensor_c
result

tensor([[0.4418, 1.6855],
        [0.7358, 0.7329]])

In [24]:
result.shape
reshaped = result.view(1,4)
reshaped

tensor([[0.4418, 1.6855, 0.7358, 0.7329]])

In [25]:
points = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(points)
points[0][1]
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [26]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [27]:
p_t = points.t()    #transpuesta
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [28]:
tensor_x = torch.tensor([1, 2, 3, 4])
tensor_x, torch.unsqueeze(tensor_x, 0)  #crea dimensión adicional sobre la misma fila

(tensor([1, 2, 3, 4]), tensor([[1, 2, 3, 4]]))

In [29]:
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [30]:
numpyArray = np.random.randn(2,2)
torch.from_numpy(numpyArray)

tensor([[-0.1764,  1.0775],
        [ 1.2984,  0.3741]], dtype=torch.float64)